PS1-CisnerosAcostaJoseEnrique/Controllers/CitiesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PS1_CisnerosAcostaJoseEnrique.Models;

namespace PS1_CisnerosAcostaJoseEnrique.Controllers
{
    public class CitiesController : Controller
    {
        private EventDbContext db = new EventDbContext();

        // GET: Cities
        public ActionResult Index()
        {
            return View(db.Cities.ToList());
        }

        // GET: Cities/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            City city = db.Cities.Find(id);
            if (city == null)
            {
                return HttpNotFound();
            }
            return View(city);
        }

        // GET: Cities/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Cities/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,nombreciudad,pais")] City city)
        {
            if (ModelState.IsValid)
            {
                db.Cities.Add(city);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(city);
        }

        // GET: Cities/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            City city = db.Cities.Find(id);
            if (city == null)
            {
                return HttpNotFound();
            }
            return View(city);
        }

        // POST: Cities/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,nombreciudad,pais")] City city)
        {
            if (ModelState.IsValid)
            {
                db.Entry(city).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(city);
        }

        // GET: Cities/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            City city = db.Cities.Find(id);
            if (city == null)
            {
                return HttpNotFound();
            }
            return View(city);
        }

        // POST: Cities/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            City city = db.Cities.Find(id);
            db.Cities.Remove(city);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PS1-CisnerosAcostaJoseEnrique/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PS1_CisnerosAcostaJoseEnrique.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

PS1-CisnerosAcostaJoseEnrique/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>Sobre la práctica</h2>
<h3>Práctica Semanal</h3>

<p>
    En su Practica semanal se evaluara lo siguiente:
</p>

<p> 1.- MVC sin autenticación, </p>
<p> 2.- Conexion a la bd, </p>
<p> 3.- DbContext </p>
<p> 4.- Migraciones </p>
<p> 5.- Modelos </p>
<p> 6.- Controladores, </p>
<p> 7.- Vistas personalizadas </p>
<p> 8.- Helpers </p>
<p> 9.- Documentación </p>
<p> 10.- Conclusiones Personales. </p>

PS1-CisnerosAcostaJoseEnrique/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>Contacto</h2>
<h3>Datos del Alumno</h3>

<img src="~/Content/img/fotomia.jpg" width="150" height="150">
<address>
    <br />
    <strong> <span class="glyphicon glyphicon-user"> </span>  Nombre:</strong> Cisneros Acosta José Enrique<br />
    <strong> <span class="glyphicon glyphicon-sound-5-1"> </span>  N° Control:</strong> 17211668<br />
    <strong> <span class="glyphicon glyphicon-info-sign"> </span>  Carrera:</strong> Ingenieria Informática<br />
    <strong> <span class="glyphicon glyphicon-star"> </span>  Semestre:</strong> 6to Semestre<br />
</address>

<address>
    <h4>Cualquier duda contacte a este correo: </h4>
    <strong> <span class="glyphicon glyphicon-send"> </span>  Correo Electronico:</strong> <a href="mailto:jose.cisneros17@tectijuana.edu.mx">jose.cisneros17@tectijuana.edu.mx</a><br />
</address>

PS1-CisnerosAcostaJoseEnrique/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

    <div class="jumbotron">
        <img src="~/Content/img/logoitt.png" class="img-rounded center-block">
        <h2 class="text-center">PRÁCTICA SEMANAL 1</h2>
        <h2 class="text-center">UNIDAD 3</h2>
        <h3 class="lead text-center">DESARROLLO DE APLICACIONES WEB</h3>
        <h3 class="lead text-center">JUAN MANUEL HERNANDEZ MARTINEZ</h3>
    </div>

<div class="row">
    <div class="col-md-4">
        <h2>Contacto</h2>
        <p>
            Cisneros Acosta Jose Enrique, más información click a Contacto en la parte superior en Contact
        </p>
        <img src="~/Content/img/fotomia.jpg" width="100" height="100">
        @Html.ActionLink("Contacto", "Contact", "Home")
    </div>
    <div class="col-md-4">
        <h2>Sobre la práctica</h2>
        <p>Si gusta saber sobre que trata la página dele click en About o en la parte superior darle click en About</p>
        <img src="~/Content/img/web.png" width="100" height="100">
        @Html.ActionLink("About", "About", "Home")
    </div>
    <div class="col-md-4">
        <h2>Ciudades</h2>
        <p>Si gusta agregar una ciudad dele click en Agregar ciudad o en la parte superior darle click en Ciudades</p>
        <img src="~/Content/img/ciudad.jpg" width="100" height="100">
        @Html.ActionLink("Agregar ciudad", "Index", "Cities")
    </div>
</div>